### ISSUE TITLE
Grading Overview

### ISSUE THREAD

**Issue by lucav17** [brynmailer/Jammming#2]
**Binding**
You can always bind your methods in other ways too such as binding in the render method or you can bind in the functions themselves using the arrow syntax!

**Passing Data**
Great job passing around different data structures!

**React Concepts**
Great job passing around state, creating components, and understanding life cycle methods!

**Grade 15/16**
Amazing job! I would suggest learning backend node and express development!

**Comment by brynmailer** [comment]
thanks!!!

**Comment by brynmailer** [comment]
If I may ask. What was the reason for me not getting a 16/16?
